"""FAIMR Plus -- SSA char-LSTM name-gender plugin.

A small bi-directional character LSTM trained on the full US SSA
baby-names corpus.  Designed to be the heavyweight fallback above
FAIMR's hybrid lookup + char-ngram LR classifier on the rare-tail
OOD slice where calibration alone cannot recover accuracy.

The plugin is OPTIONAL:
  - Core FAIMR works without it
  - Plugin import is lazy; nothing under faimr_plus.ssa_char_lstm
    is loaded unless an explicit call asks for it
  - Trained weights live in faimr_plus/ssa_char_lstm/weights.pt
    (~1MB), generated by `python -m faimr_plus.ssa_char_lstm.train`

Public API: see predict.py for `predict_p_female(names: list[str])`.
"""
